// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("API.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Akıllı Saat açıklaması",
                            ImageUrl = "1.jpg",
                            IsActive = true,
                            Name = "Apple Watch Series 7",
                            Price = 10000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 2,
                            Description = "Akıllı Saat açıklaması",
                            ImageUrl = "2.jpg",
                            IsActive = true,
                            Name = "Apple Watch Series 8",
                            Price = 20000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 3,
                            Description = "Akıllı Saat açıklaması",
                            ImageUrl = "3.jpg",
                            IsActive = false,
                            Name = "Apple Watch Series 9",
                            Price = 30000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 4,
                            Description = "Akıllı Saat açıklaması",
                            ImageUrl = "4.jpg",
                            IsActive = true,
                            Name = "Apple Watch Series 10",
                            Price = 40000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 5,
                            Description = "Akıllı Saat açıklaması",
                            ImageUrl = "5.jpg",
                            IsActive = true,
                            Name = "Apple Watch Series 11",
                            Price = 50000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 6,
                            Description = "Akıllı Saat açıklaması",
                            ImageUrl = "6.jpg",
                            IsActive = true,
                            Name = "Apple Watch Series 12",
                            Price = 60000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 7,
                            Description = "Akıllı Saat açıklaması",
                            ImageUrl = "7.jpg",
                            IsActive = true,
                            Name = "Apple Watch Series 13",
                            Price = 70000m,
                            Stock = 100
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
